### PR TITLE
Fixes to wisdom.rb

### PR DESCRIPTION
**Pull request by maxehmookau**
"Live, Laugh, Love" appeared in my terminal and I immedately felt a flashes of red-hot rage.

Also, those flowers aren't trees.

### CODE REVIEW

**Comment by jsrn** [comment]
Dogs also aren't trees.

**Comment by maxehmookau** [comment]
> Dogs also aren't trees.

Once a year, all of their fluff (leaves) fall out. Much like trees.
They get bigger with age. Like trees.
They're fiercely loyal. Like trees. (When was the last time a tree ever betrayed you?)

So.. yeah.

**Comment by jsrn** [comment]
I'd only describe myself as an amateur taxonomist, but... it checks out. Thank you for your contribution.

**Comment by maxehmookau** [comment]
That's how you open source.

**Pull request merged**
